SchoolOABase/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.views.static import serve
from system.views import IndexView, LoginView, LogoutView, mytest
from tools import views as tools_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='temp-index'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('system/', include('system.urls')),
    path('base/', include('base.urls', namespace='base')),
    path('attendance/', include('attendance.urls', namespace='attendance')),

    path('mytest/', mytest),

]
urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {"document_root": settings.MEDIA_ROOT}),
]

apps/system/urls.py
from django.urls import path
from . import views, views_instructor, views_menu, views_permission, views_group, views_home

app_name = 'system'
urlpatterns = [
    path('home/profile/', views_home.InstructorProfileView.as_view(), name='home-profile'),
    path('home/login_pwd_change/', views_home.LoginPwdChangeView.as_view(), name='home-login_pwd_change'),
    path('home/private_pwd_change/', views_home.PrivatePwdChangeView.as_view(), name='home-private_pwd_change'),

    path('', views.IndexView.as_view(), name='system-index'),
    path('instructor/', views_instructor.InstructorView.as_view(), name='instructor'),
    path('instructor/list/', views_instructor.InstructorListView.as_view(), name='instructor-list'),
    path('instructor/create/', views_instructor.InstructorCreateView.as_view(), name='instructor-create'),
    path('instructor/update/', views_instructor.InstructorUpdateView.as_view(), name='instructor-update'),
    path('instructor/password_change/', views_instructor.PasswordChangeView.as_view(),
         name='instructor-password-change'),
    path('instructor/delete/', views_instructor.InstructorDeleteView.as_view(), name='instructor-delete'),
    path('instructor/enable/', views_instructor.InstructorEnableView.as_view(), name='instructor-enable'),
    path('instructor/disable/', views_instructor.InstructorDisableView.as_view(), name='instructor-disable'),

    path('menu/', views_menu.MenuView.as_view(), name='menu'),
    path('menu/edit/', views_menu.MenuEditView.as_view(), name='menu-edit'),
    path('menu/delete/', views_menu.MenuDeleteView.as_view(), name='menu-delete'),
    path('menu/list/', views_menu.MenuListView.as_view(), name='menu-list'),

    path('permission/', views_permission.PermissionView.as_view(), name='permission'),
    path('permission/edit/', views_permission.PermissionEditView.as_view(), name='permission-edit'),
    path('permission/delete/', views_permission.PermissionDeleteView.as_view(), name='permission-delete'),
    path('permission/list/', views_permission.PermissionListView.as_view(), name='permission-list'),

    path('group/', views_group.GroupView.as_view(), name='group'),
    path('group/edit/', views_group.GroupEditView.as_view(), name='group-edit'),
    path('group/delete/', views_group.GroupDeleteView.as_view(), name='group-delete'),
    path('group/list/', views_group.GroupListView.as_view(), name='group-list'),
    path('group/group2instructor/', views_group.Group2InstructorView.as_view(), name="group-group2instructor"),
    path('group/group2menu/', views_group.Group2MenuView.as_view(), name="group-group2menu"),
    path('group/group2menu_list/', views_group.Group2MenuListView.as_view(), name="group-group2menu_list"),
    path('group/group2permission/', views_group.Group2PermissionView.as_view(), name="group-group2permission"),
    # path('demo/', views.demo, name='system-demo'),
    # path('demoview1/', permission_required('base.add_department')(views.DemoView.as_view()), name='viewAssetHistory'),
    # path('demoview2/', permission_required('base.change_department')(views.DemoView.as_view()),
    #     name='viewAssetHistory'),
]

apps/system/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, AbstractBaseUser
from django.contrib.auth.models import Group, Permission


class Menu(models.Model):
    """
    菜单
    """
    name = models.CharField(max_length=30, unique=True, verbose_name='菜单名')
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.SET_NULL, verbose_name='父菜单')
    icon = models.CharField(max_length=50, null=True, blank=True, verbose_name='图标')
    url = models.CharField(max_length=128, null=True, blank=True, verbose_name='链接')
    number = models.CharField(max_length=20, null=True, blank=True, verbose_name="编号")
    # code = models.CharField(max_length=30, unique=True, default='', verbose_name='编码')
    groups = models.ManyToManyField(to=Group, verbose_name="角色")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '菜单'
        verbose_name_plural = verbose_name
        ordering = ['number']

    @classmethod
    def get_menu_by_request(cls, url):
        return dict(menu=Menu.objects.get(url=url))

    @classmethod
    def get_menu_by_request_url(cls, url):
        try:
            return dict(menu=Menu.objects.get(url=url))
        except:
            return None


class Instructor(AbstractUser):
    '''
    用户
    '''
    name = models.CharField(max_length=20, default='', verbose_name='姓名')
    gender = models.CharField(max_length=2, choices=(('男', '男'), ('女', '女')), default='男', verbose_name='性别')
    mobile = models.CharField(max_length=11, unique=True, default='', verbose_name='手机号')
    email = models.EmailField(max_length=30, verbose_name='邮箱')
    birthday = models.DateField(null=True, blank=True, verbose_name='出生日期')
    headimage = models.ImageField(upload_to='images/instructor/headimage', default='images/default.jpg', max_length=100,
                                  null=True, blank=True, verbose_name='头像')
    department = models.ForeignKey('base.Department', null=True, blank=True, on_delete=models.SET_NULL,
                                   verbose_name='部门')
    post = models.CharField(max_length=50, null=True, blank=True, verbose_name='职位')
    is_manager = models.BooleanField(default=False, verbose_name='是部门经理')
    superior = models.ForeignKey('self', null=True, blank=True, on_delete=models.SET_NULL, verbose_name='上级主管')
    private_password = models.CharField(max_length=128, null=True, verbose_name='私有密码')

    class Meta:
        verbose_name = '教师'
        verbose_name_plural = verbose_name
        ordering = ['id']

        permissions = (
            ("change_password", "基础数据.教师.修改密码"),
            ("enable_user", "基础数据.教师.启用用户"),
            ("disable_user", "基础数据.教师.禁用用户"),
        )

    def __str__(self):
        return self.name + ' ' + self.gender + ' '  # + self.department.name + self.mobile + ' ' + self.email

apps/system/forms.py
import re
from django import forms
from django.contrib.auth import get_user_model
from . import models
from django.contrib.auth.models import Permission, Group
from django.db.models import ImageField

Instructor = get_user_model()


class LoginForm(forms.Form):
    username = forms.CharField(required=True, error_messages={"requeired": "请填写用户名"})
    password = forms.CharField(required=True, error_messages={"requeired": "请填写密码"})


class InstructorCreateForm(forms.ModelForm):
    password = forms.CharField(
        required=True,
        min_length=6,
        max_length=20,
        error_messages={
            "required": "密码不能为空",
            "min_length": "密码长度最少6位数",
        }
    )

    confirm_password = forms.CharField(
        required=True,
        min_length=6,
        max_length=20,
        error_messages={
            "required": "确认密码不能为空",
            "min_length": "密码长度最少6位数",
        }
    )

    class Meta:
        model = Instructor
        fields = [
            'name', 'gender', 'birthday', 'username', 'mobile', 'email',
            'department', 'post', 'superior', 'is_active', 'password', 'groups', 'is_manager'
        ]

        error_messages = {
            "name": {"required": "姓名不能为空"},
            "username": {"required": "用户名不能为空"},
            "email": {"required": "邮箱不能为空"},
            "mobile": {
                "required": "手机号码不能为空",
                "max_length": "输入有效的手机号码",
                "min_length": "输入有效的手机号码"
            }
        }

    def clean(self):
        cleaned_data = super(InstructorCreateForm, self).clean()
        username = cleaned_data.get("username")
        mobile = cleaned_data.get("mobile", "")
        email = cleaned_data.get("email")
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if Instructor.objects.filter(username=username).count():
            raise forms.ValidationError('用户名：{}已存在'.format(username))

        if password != confirm_password:
            raise forms.ValidationError("两次密码输入不一致")

        if Instructor.objects.filter(mobile=mobile).count():
            raise forms.ValidationError('手机号码：{}已存在'.format(mobile))

        REGEX_MOBILE = "^1[3578]\d{9}$|^147\d{8}$|^176\d{8}$"
        if not re.match(REGEX_MOBILE, mobile):
            raise forms.ValidationError("手机号码非法")

        if Instructor.objects.filter(email=email).count():
            raise forms.ValidationError('邮箱：{}已存在'.format(email))


class InstructorProfileForm(forms.ModelForm):
    headimage = ImageField(upload_to='images/instructor/headimage',
                           default='images/default.jpg', max_length=100,
                           null=True, blank=True, verbose_name='头像')

    class Meta:
        model = Instructor
        fields = ['birthday', 'mobile', 'email', 'gender', 'headimage']


class InstructorUpdateForm(forms.ModelForm):
    class Meta:
        model = Instructor
        fields = [
            'name', 'gender', 'birthday', 'username', 'mobile', 'email',
            'department', 'post', 'superior', 'is_active', 'groups', 'is_manager'
        ]

        error_messages = {
            "name": {"required": "姓名不能为空"},
            "username": {"required": "用户名不能为空"},
            "email": {"required": "邮箱不能为空"},
            "mobile": {
                "required": "手机号码不能为空",
                "max_length": "输入有效的手机号码",
                "min_length": "输入有效的手机号码"
            }
        }


class PasswordChangeForm(forms.Form):
    password = forms.CharField(
        required=True,
        min_length=6,
        max_length=20,
        error_messages={
            "required": u"密码不能为空"
        })

    confirm_password = forms.CharField(
        required=True,
        min_length=6,
        max_length=20,
        error_messages={
            "required": u"确认密码不能为空"
        })

    def clean(self):
        cleaned_data = super(PasswordChangeForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")
        if password != confirm_password:
            raise forms.ValidationError("两次密码输入不一致")


class LoginPwdChangeForm(forms.Form):
    old_password = forms.CharField(
        required=True,
        min_length=6,
        max_length=20,
        error_messages={
            "required": u"原密码不能为空"
        })

    new_password = forms.CharField(
        required=True,
        min_length=6,
        max_length=20,
        error_messages={
            "required": u"新密码不能为空"
        })

    confirm_password = forms.CharField(
        required=True,
        min_length=6,
        max_length=20,
        error_messages={
            "required": u"确认密码不能为空"
        })

    def clean(self):
        cleaned_data = super(LoginPwdChangeForm, self).clean()
        new_password = cleaned_data.get("new_password")
        confirm_password = cleaned_data.get("confirm_password")
        if new_password != confirm_password:
            raise forms.ValidationError("两次密码输入不一致")


class PrivatePwdChangeForm(forms.Form):
    login_password = forms.CharField(
        required=True,
        min_length=6,
        max_length=20,
        error_messages={
            "required": u"原密码不能为空"
        })

    new_password = forms.CharField(
        required=True,
        min_length=6,
        max_length=20,
        error_messages={
            "required": u"新密码不能为空"
        })

    confirm_password = forms.CharField(
        required=True,
        min_length=6,
        max_length=20,
        error_messages={
            "required": u"确认密码不能为空"
        })

    def clean(self):
        cleaned_data = super(PrivatePwdChangeForm, self).clean()
        new_password = cleaned_data.get("new_password")
        confirm_password = cleaned_data.get("confirm_password")
        if new_password != confirm_password:
            raise forms.ValidationError("两次密码输入不一致")

class MenuForm(forms.ModelForm):
    class Meta:
        model = models.Menu
        fields = ['name', 'icon', 'parent', 'url', 'number']


class PermissionForm(forms.ModelForm):
    class Meta:
        model = Permission
        fields = ['name', 'content_type', 'codename']


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['name']

apps/system/views.py
import json, re
from django.shortcuts import render, HttpResponse, get_object_or_404, redirect
from django.views.generic.base import View, TemplateView
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.hashers import make_password
from django.urls import reverse
from django.db.models import Q
from .mixin import LoginRequiredMixin
from .forms import LoginForm
from tools.my_menus import MenuCollection

User = get_user_model()


class IndexView(LoginRequiredMixin, View):

    def get(self, request):
        return render(request, 'system/index.html')


class LoginView(View):

    def get(self, request):
        if not request.user.is_authenticated:
            return render(request, 'system/login.html')
        else:
            return HttpResponseRedirect(reverse('system-index'))

    def post(self, request):
        redirect_to = request.GET.get('next', '/')
        login_form = LoginForm(request.POST)
        res = dict(login_form=login_form)
        print(request.META.get('REMOTE_ADDR'))
        if login_form.is_valid():
            user_name = request.POST['username']
            pass_word = request.POST['password']
            user = authenticate(username=user_name, password=pass_word)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    my_menu = MenuCollection()
                    my_menu.get_my_menu(request)
                    return HttpResponseRedirect(redirect_to)
                else:
                    res['msg'] = '用户未激活！'
            else:
                res['msg'] = '用户名或密码错误！'
        else:
            res['msg'] = '用户和密码不能为空！'
        return render(request, 'system/login.html', res)


class LogoutView(View):

    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse('login'))




def mytest(request):
    return render(request, 'mytest.html')

templates/system/instructors/instructor.html
{% extends "base-main.html" %}
{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/plugins/dataTables/jquery.datatables.min.css' %}">
    <link href="/static/css/plugins/sweetalert/sweetalert.css" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox ">
                <div class="ibox-title">
                    <h5>教师信息列表</h5>
                    <button type="button" id="btnRefresh" class="btn btn-default">
                        <i class="glyphicon glyphicon-repeat"></i>刷新
                    </button>
                    {% if perms.system.add_instructor %}
                        <button type="button" id="btnCreate" class="btn btn-default">
                            <i class="glyphicon glyphicon-plus"></i>新增
                        </button>
                    {% endif %}
                    {% if perms.system.delete_instructor %}
                        <button type="button" id="btnDelete" class="btn btn-default">
                            <i class="glyphicon glyphicon-trash"></i>删除
                        </button>
                    {% endif %}
                    {% if perms.system.enable_user %}
                        <button type="button" id="btnEnable" class="btn btn-default">
                            <i class="glyphicon glyphicon-ok-circle"></i>启用
                        </button>
                    {% endif %}
                    {% if perms.system.disable_user %}
                        <button type="button" id="btnDisable" class="btn btn-default">
                            <i class="glyphicon glyphicon-ban-circle"></i>禁用
                        </button>
                    {% endif %}
                    <div class="ibox-tools">
                        <form class="form-inline">
                            <div class="form-group">
                                <label>用户状态：</label>
                                <select id="select" name="select" class="form-control">
                                    <option style='text-align:center' value=''>-----所有-----</option>
                                    <option value="True">启用</option>
                                    <option value="False">禁用</option>
                                </select>
                            </div>
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                        </form>
                    </div>
                </div>
                <div class="ibox-content">
                    <div class="table-responsive">
                        <table id="dtbList" class="display table-striped table-bordered table-hover table-condensed"
                               style="width:100%">
                            <thead>
                            <tr>
                                <th>
                                    <input type="checkbox" id="checkAll" class="group-checkable"
                                           style="margin-left: -8px"></th>
                                <th>编号</th>
                                <th>姓名</th>
                                <th>性别</th>
                                <th>手机号</th>
                                <th>电子邮箱</th>
                                <th>所属部门</th>
                                <th>职位</th>
                                <th>上级</th>
                                <th>状态</th>
                                <th>操作</th>
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script src="/static/js/plugins/sweetalert/sweetalert.min.js"></script>
    <script src="{% static 'js/plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/plugins/datatables/dataTables.const.js' %}"></script>
    <script>
        var oDataTable = null;
        $(function () {
            oDataTable = initTable();

            //显示列表
            function initTable() {
                var oTable = $('#dtbList').DataTable({
                    "paging": true,
                    "pagingType": "full_numbers",
                    "lengthMenu": [20, 50, 100, 200],
                    "processing": true,
                    "searching": true, //是否开启搜索
                    //"serverSide": true,//开启服务器获取数据
                    "order": [[1, "desc"]], //默认排序
                    "ajax": {
                        "url": "{% url 'system:instructor-list' %}",
                        "data": function (d) {
                            d.select = $("#select").val();
                        }
                    },
                    columns: [
                        DATATABLES_CONSTANT.DATA_TABLES.COLUMN.CHECKBOX,
                        {"title": "编号", "data": "id"},
                        {"title": "姓名", "data": "name"},
                        {"title": "性别", "data": "gender"},
                        {"title": "手机号", "data": "mobile"},
                        {"title": "电子邮箱", "data": "email"},
                        {"title": "所属部门", "data": "department__name"},
                        {"title": "职位", "data": "post"},
                        {"title": "上级", "data": "superior__name"},
                        {
                            "title": "状态",
                            "data": "is_active",
                            render: function (data, type, row, meta) {
                                if (data) {
                                    return "可用";
                                } else {
                                    return "禁用";
                                }
                            }
                        },
                        {
                            "title": "操作",
                            data: "id",
                            width: "10%",
                            align: "right",
                            bSortable: false,
                            render:
                                function (data, type, row, meta) {
                                    var ret = "";
                                    {% if perms.system.change_instructor %}
                                        ret = ret + "<button title='详情-编辑' onclick='doUpdate("
                                            + data + ")'><i class='glyphicon glyphicon-pencil'></i></button>";
                                    {% endif %}
                                    {% if perms.system.change_password %}
                                        ret = ret + "<button name='btnChangepasswd' title='修改密码' onclick='doChangepasswd("
                                            + data + ")'><i class='glyphicon glyphicon-asterisk'></i></button>";
                                    {% endif %}
                                    {% if perms.system.delete_instructor %}
                                        ret = ret + "<button name='btnConfig' title='删除' onclick='doDelete("
                                            + data + ")'><i class='glyphicon glyphicon-trash'></i></button>";
                                    {% endif %}
                                    return ret;
                                }
                        }
                    ],
                    "language":
                        { // 定义语言
                            "sProcessing":
                                "加载中...",
                            "sLengthMenu":
                                "每页显示 _MENU_ 条记录",
                            "sZeroRecords":
                                "没有匹配的结果",
                            "sInfo":
                                "显示第 _START_ 至 _END_ 项结果，共 _TOTAL_ 项",
                            "sInfoEmpty":
                                "显示第 0 至 0 项结果，共 0 项",
                            "sInfoFiltered":
                                "(由 _MAX_ 项结果过滤)",
                            "sInfoPostFix":
                                "",
                            "sSearch":
                                "搜索:",
                            "sUrl":
                                "",
                            "sEmptyTable":
                                "表中数据为空",
                            "sLoadingRecords":
                                "载入中...",
                            "sInfoThousands":
                                ",",
                            "oPaginate":
                                {
                                    "sFirst":
                                        "首页 ",
                                    "sPrevious":
                                        "上一页 ",
                                    "sNext":
                                        "下一页 ",
                                    "sLast":
                                        "末页"
                                },
                            "oAria":
                                {
                                    "sSortAscending":
                                        ": 以升序排列此列",
                                    "sSortDescending":
                                        ": 以降序排列此列"
                                }
                        },
                });
                return oTable;
            }
        });

        $("#btnRefresh").click(function () {
            oDataTable.ajax.reload();
        });


        function doChangepasswd(id) {
            showPopup('修改密码', 500, 420, "{% url 'system:instructor-password-change' %}" + '?id=' + id);
        }

        $("#btnCreate").click(function () {
            showPopup('增加教师信息', 800, 700, "{% url 'system:instructor-create' %}");
        });

        // 跳转到教师详情页面
        function doUpdate(id) {
            showPopup('修改教师信息', 800, 700, "{% url 'system:instructor-update' %}" + '?id=' + id);
        }

        //删除
        function doDelete(id) {
            deleteData("{% url 'system:instructor-delete' %}", "{{ csrf_token }}", oDataTable.ajax.reload, id);
        }

        //批量删除
        $("#btnDelete").click(function () {
            deleteData("{% url 'system:instructor-delete' %}", "{{ csrf_token }}", oDataTable.ajax.reload);
        });

        function SetInstructoeEnable(state) {
            oper = '启用';
            urlPost = "{% url 'system:instructor-enable' %}";
            if (!state) {
                oper = '禁用';
                urlPost = "{% url 'system:instructor-disable' %}";
            }
            if ($("input[name='checkList']:checked").length == 0) {
                swal('请选择要' + oper + '的用户', "", "warning");
                return;
            }

            var arrId = new Array();
            $("input[name='checkList']:checked").each(function () {
                //alert($(this).val());
                arrId.push($(this).val());
            });

            sId = arrId.join(',');
            swal({
                    title: "确定" + oper + "吗？",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "确定",
                    cancelButtonText: "取消",
                    closeOnConfirm: false,
                },
                function (isConfirm) {
                    if (isConfirm) {
                        $.ajax({
                            type: "POST",
                            url: urlPost,
                            data: {"id": sId, csrfmiddlewaretoken: '{{ csrf_token }}'},
                            cache: false,
                            success: function (msg) {
                                if (msg.result) {
                                    swal(oper + '用户成功', "", "success");
                                    oDataTable.ajax.reload();
                                } else {
                                    swal(oper + '用户失败', "", "warning");
                                }
                                return;
                            }
                        });
                    }
                }
            );
        }

        //批量启用
        $("#btnEnable").click(
            function () {
                SetInstructoeEnable(true);
            }
        );

        //批量禁用
        $("#btnDisable").click(
            function () {
                SetInstructoeEnable(false);
            }
        );

        $("#select").change(function () {
            //alert($("#select").val())
            oDataTable.ajax.reload();
        });
    </script>
{% endblock %}

templates/system/instructors/passwd_change.html
{% extends 'base-popup.html' %}
{% load staticfiles %}
{% block content %}
    <div class="ibox-content">
        <form class="form-horizontal" id="changePasswordForm" method="post">
            {% csrf_token %}
            <input type="hidden" name='id' value="{{ instructor.id }}"/>
            <input type="hidden" name='instructor' value="save"/>
            <legend style="overflow:hidden">
                <h4 style="width: 200px;float: left">基本信息</h4>
            </legend>
            <div class="form-group row">
                <label class="col-3 col-form-label">姓名</label>
                <div class="col-8">
                    <input class="form-control" type="text" disabled value="{{ instructor.name }}"></input>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-3 col-form-label">用户名</label>
                <div class="col-8">
                    <input class="form-control" type="text" disabled value="{{ instructor.username }}"></input>
                </div>
            </div>
            <legend>
                <h4>密码信息</h4>
            </legend>
            <div class="form-group row">
                <label class="col-3 col-control-label">密码</label>
                <div class="col-8">
                    <input class="form-control" name="password" type="password" value=""/>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-3 col-control-label">确认密码</label>
                <div class="col-8">
                    <input class="form-control" name="confirm_password" type="password" value=""/>
                </div>
            </div>
            <div class="hr-line-dashed"></div>
            <div class="form-group row">
                <div style="margin:0 auto">
                    <button type="button" id="btnClose" class="btn btn-default margin-right ">关闭</button>
                    <button type="button" id="btnSave" class="btn btn-info margin-right ">确定</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

{% block javascripts %}
    <script type="text/javascript">
        $("#btnSave").click(function () {
            var data = $("#changePasswordForm").serialize();
            $.ajax({
                type: $("#changePasswordForm").attr('method'),
                url: "{% url 'system:instructor-password-change' %}",
                data: data,
                cache: false,
                success: function (msg) {
                    if (msg.status == 'success') {
                        swal({
                            title: "密码修改成功！",
                            type: "success",
                            confirmButtonText: "确定",
                            closeOnConfirm: true
                        }, function () {
                            parent.closePopup('#popupChangPassword');
                        });
                    } else if (msg.status == 'fail') {
                        swal({
                            title: msg.error_messages,
                            type: "warning",
                            confirmButtonColor: "#DD6B55",
                            confirmButtonText: "确定",
                            closeOnConfirm: false
                        });
                    }
                    return;
                }
            });
        });


        /*点取消刷新页面*/
        $("#btnClose").click(function () {
            window.parent.closePopup();
        });
    </script>

{% endblock %}