SchoolOABase/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.views.static import serve
from system.views import IndexView, LoginView, LogoutView, mytest
from tools import views as tools_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='temp-index'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('system/', include('system.urls')),
    path('base/', include('base.urls', namespace='base')),
    path('attendance/', include('attendance.urls', namespace='attendance')),

    path('mytest/', mytest),

]
urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {"document_root": settings.MEDIA_ROOT}),
]

apps/system/urls.py
from django.urls import path
from . import views, views_instructor, views_menu, views_permission, views_group, views_home

app_name = 'system'
urlpatterns = [
    path('home/profile/', views_home.InstructorProfileView.as_view(), name='home-profile'),
    path('home/login_pwd_change/', views_home.LoginPwdChangeView.as_view(), name='home-login_pwd_change'),
    path('home/private_pwd_change/', views_home.PrivatePwdChangeView.as_view(), name='home-private_pwd_change'),

    path('', views.IndexView.as_view(), name='system-index'),
    path('instructor/', views_instructor.InstructorView.as_view(), name='instructor'),
    path('instructor/list/', views_instructor.InstructorListView.as_view(), name='instructor-list'),
    path('instructor/create/', views_instructor.InstructorCreateView.as_view(), name='instructor-create'),
    path('instructor/update/', views_instructor.InstructorUpdateView.as_view(), name='instructor-update'),
    path('instructor/password_change/', views_instructor.PasswordChangeView.as_view(),
         name='instructor-password-change'),
    path('instructor/delete/', views_instructor.InstructorDeleteView.as_view(), name='instructor-delete'),
    path('instructor/enable/', views_instructor.InstructorEnableView.as_view(), name='instructor-enable'),
    path('instructor/disable/', views_instructor.InstructorDisableView.as_view(), name='instructor-disable'),

    path('menu/', views_menu.MenuView.as_view(), name='menu'),
    path('menu/edit/', views_menu.MenuEditView.as_view(), name='menu-edit'),
    path('menu/delete/', views_menu.MenuDeleteView.as_view(), name='menu-delete'),
    path('menu/list/', views_menu.MenuListView.as_view(), name='menu-list'),

    path('permission/', views_permission.PermissionView.as_view(), name='permission'),
    path('permission/edit/', views_permission.PermissionEditView.as_view(), name='permission-edit'),
    path('permission/delete/', views_permission.PermissionDeleteView.as_view(), name='permission-delete'),
    path('permission/list/', views_permission.PermissionListView.as_view(), name='permission-list'),

    path('group/', views_group.GroupView.as_view(), name='group'),
    path('group/edit/', views_group.GroupEditView.as_view(), name='group-edit'),
    path('group/delete/', views_group.GroupDeleteView.as_view(), name='group-delete'),
    path('group/list/', views_group.GroupListView.as_view(), name='group-list'),
    path('group/group2instructor/', views_group.Group2InstructorView.as_view(), name="group-group2instructor"),
    path('group/group2menu/', views_group.Group2MenuView.as_view(), name="group-group2menu"),
    path('group/group2menu_list/', views_group.Group2MenuListView.as_view(), name="group-group2menu_list"),
    path('group/group2permission/', views_group.Group2PermissionView.as_view(), name="group-group2permission"),
    # path('demo/', views.demo, name='system-demo'),
    # path('demoview1/', permission_required('base.add_department')(views.DemoView.as_view()), name='viewAssetHistory'),
    # path('demoview2/', permission_required('base.change_department')(views.DemoView.as_view()),
    #     name='viewAssetHistory'),
]

apps/system/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, AbstractBaseUser
from django.contrib.auth.models import Group, Permission


class Menu(models.Model):
    """
    菜单
    """
    name = models.CharField(max_length=30, unique=True, verbose_name='菜单名')
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.SET_NULL, verbose_name='父菜单')
    icon = models.CharField(max_length=50, null=True, blank=True, verbose_name='图标')
    url = models.CharField(max_length=128, null=True, blank=True, verbose_name='链接')
    number = models.CharField(max_length=20, null=True, blank=True, verbose_name="编号")
    # code = models.CharField(max_length=30, unique=True, default='', verbose_name='编码')
    groups = models.ManyToManyField(to=Group, verbose_name="角色")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '菜单'
        verbose_name_plural = verbose_name
        ordering = ['number']

    @classmethod
    def get_menu_by_request(cls, url):
        return dict(menu=Menu.objects.get(url=url))

    @classmethod
    def get_menu_by_request_url(cls, url):
        try:
            return dict(menu=Menu.objects.get(url=url))
        except:
            return None


class Instructor(AbstractUser):
    '''
    用户
    '''
    name = models.CharField(max_length=20, default='', verbose_name='姓名')
    gender = models.CharField(max_length=2, choices=(('男', '男'), ('女', '女')), default='男', verbose_name='性别')
    mobile = models.CharField(max_length=11, unique=True, default='', verbose_name='手机号')
    email = models.EmailField(max_length=30, verbose_name='邮箱')
    birthday = models.DateField(null=True, blank=True, verbose_name='出生日期')
    headimage = models.ImageField(upload_to='images/instructor/headimage', default='images/default.jpg', max_length=100,
                                  null=True, blank=True, verbose_name='头像')
    department = models.ForeignKey('base.Department', null=True, blank=True, on_delete=models.SET_NULL,
                                   verbose_name='部门')
    post = models.CharField(max_length=50, null=True, blank=True, verbose_name='职位')
    is_manager = models.BooleanField(default=False, verbose_name='是部门经理')
    superior = models.ForeignKey('self', null=True, blank=True, on_delete=models.SET_NULL, verbose_name='上级主管')
    private_password = models.CharField(max_length=128, null=True, verbose_name='私有密码')

    class Meta:
        verbose_name = '教师'
        verbose_name_plural = verbose_name
        ordering = ['id']

        permissions = (
            ("change_password", "基础数据.教师.修改密码"),
            ("enable_user", "基础数据.教师.启用用户"),
            ("disable_user", "基础数据.教师.禁用用户"),
        )

    def __str__(self):
        return self.name + ' ' + self.gender + ' '  # + self.department.name + self.mobile + ' ' + self.email

apps/system/forms.py
import re
from django import forms
from django.contrib.auth import get_user_model
from . import models
from django.contrib.auth.models import Permission, Group
from django.db.models import ImageField

Instructor = get_user_model()


class LoginForm(forms.Form):
    username = forms.CharField(required=True, error_messages={"requeired": "请填写用户名"})
    password = forms.CharField(required=True, error_messages={"requeired": "请填写密码"})


class InstructorCreateForm(forms.ModelForm):
    password = forms.CharField(
        required=True,
        min_length=6,
        max_length=20,
        error_messages={
            "required": "密码不能为空",
            "min_length": "密码长度最少6位数",
        }
    )

    confirm_password = forms.CharField(
        required=True,
        min_length=6,
        max_length=20,
        error_messages={
            "required": "确认密码不能为空",
            "min_length": "密码长度最少6位数",
        }
    )

    class Meta:
        model = Instructor
        fields = [
            'name', 'gender', 'birthday', 'username', 'mobile', 'email',
            'department', 'post', 'superior', 'is_active', 'password', 'groups', 'is_manager'
        ]

        error_messages = {
            "name": {"required": "姓名不能为空"},
            "username": {"required": "用户名不能为空"},
            "email": {"required": "邮箱不能为空"},
            "mobile": {
                "required": "手机号码不能为空",
                "max_length": "输入有效的手机号码",
                "min_length": "输入有效的手机号码"
            }
        }

    def clean(self):
        cleaned_data = super(InstructorCreateForm, self).clean()
        username = cleaned_data.get("username")
        mobile = cleaned_data.get("mobile", "")
        email = cleaned_data.get("email")
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if Instructor.objects.filter(username=username).count():
            raise forms.ValidationError('用户名：{}已存在'.format(username))

        if password != confirm_password:
            raise forms.ValidationError("两次密码输入不一致")

        if Instructor.objects.filter(mobile=mobile).count():
            raise forms.ValidationError('手机号码：{}已存在'.format(mobile))

        REGEX_MOBILE = "^1[3578]\d{9}$|^147\d{8}$|^176\d{8}$"
        if not re.match(REGEX_MOBILE, mobile):
            raise forms.ValidationError("手机号码非法")

        if Instructor.objects.filter(email=email).count():
            raise forms.ValidationError('邮箱：{}已存在'.format(email))


class InstructorProfileForm(forms.ModelForm):
    headimage = ImageField(upload_to='images/instructor/headimage',
                           default='images/default.jpg', max_length=100,
                           null=True, blank=True, verbose_name='头像')

    class Meta:
        model = Instructor
        fields = ['birthday', 'mobile', 'email', 'gender', 'headimage']


class InstructorUpdateForm(forms.ModelForm):
    class Meta:
        model = Instructor
        fields = [
            'name', 'gender', 'birthday', 'username', 'mobile', 'email',
            'department', 'post', 'superior', 'is_active', 'groups', 'is_manager'
        ]

        error_messages = {
            "name": {"required": "姓名不能为空"},
            "username": {"required": "用户名不能为空"},
            "email": {"required": "邮箱不能为空"},
            "mobile": {
                "required": "手机号码不能为空",
                "max_length": "输入有效的手机号码",
                "min_length": "输入有效的手机号码"
            }
        }


class PasswordChangeForm(forms.Form):
    password = forms.CharField(
        required=True,
        min_length=6,
        max_length=20,
        error_messages={
            "required": u"密码不能为空"
        })

    confirm_password = forms.CharField(
        required=True,
        min_length=6,
        max_length=20,
        error_messages={
            "required": u"确认密码不能为空"
        })

    def clean(self):
        cleaned_data = super(PasswordChangeForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")
        if password != confirm_password:
            raise forms.ValidationError("两次密码输入不一致")


class LoginPwdChangeForm(forms.Form):
    old_password = forms.CharField(
        required=True,
        min_length=6,
        max_length=20,
        error_messages={
            "required": u"原密码不能为空"
        })

    new_password = forms.CharField(
        required=True,
        min_length=6,
        max_length=20,
        error_messages={
            "required": u"新密码不能为空"
        })

    confirm_password = forms.CharField(
        required=True,
        min_length=6,
        max_length=20,
        error_messages={
            "required": u"确认密码不能为空"
        })

    def clean(self):
        cleaned_data = super(LoginPwdChangeForm, self).clean()
        new_password = cleaned_data.get("new_password")
        confirm_password = cleaned_data.get("confirm_password")
        if new_password != confirm_password:
            raise forms.ValidationError("两次密码输入不一致")


class PrivatePwdChangeForm(forms.Form):
    login_password = forms.CharField(
        required=True,
        min_length=6,
        max_length=20,
        error_messages={
            "required": u"原密码不能为空"
        })

    new_password = forms.CharField(
        required=True,
        min_length=6,
        max_length=20,
        error_messages={
            "required": u"新密码不能为空"
        })

    confirm_password = forms.CharField(
        required=True,
        min_length=6,
        max_length=20,
        error_messages={
            "required": u"确认密码不能为空"
        })

    def clean(self):
        cleaned_data = super(PrivatePwdChangeForm, self).clean()
        new_password = cleaned_data.get("new_password")
        confirm_password = cleaned_data.get("confirm_password")
        if new_password != confirm_password:
            raise forms.ValidationError("两次密码输入不一致")

class MenuForm(forms.ModelForm):
    class Meta:
        model = models.Menu
        fields = ['name', 'icon', 'parent', 'url', 'number']


class PermissionForm(forms.ModelForm):
    class Meta:
        model = Permission
        fields = ['name', 'content_type', 'codename']


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['name']

apps/system/views.py
import json, re
from django.shortcuts import render, HttpResponse, get_object_or_404, redirect
from django.views.generic.base import View, TemplateView
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.hashers import make_password
from django.urls import reverse
from django.db.models import Q
from .mixin import LoginRequiredMixin
from .forms import LoginForm
from tools.my_menus import MenuCollection

User = get_user_model()


class IndexView(LoginRequiredMixin, View):

    def get(self, request):
        return render(request, 'system/index.html')


class LoginView(View):

    def get(self, request):
        if not request.user.is_authenticated:
            return render(request, 'system/login.html')
        else:
            return HttpResponseRedirect(reverse('system-index'))

    def post(self, request):
        redirect_to = request.GET.get('next', '/')
        login_form = LoginForm(request.POST)
        res = dict(login_form=login_form)
        print(request.META.get('REMOTE_ADDR'))
        if login_form.is_valid():
            user_name = request.POST['username']
            pass_word = request.POST['password']
            user = authenticate(username=user_name, password=pass_word)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    my_menu = MenuCollection()
                    my_menu.get_my_menu(request)
                    return HttpResponseRedirect(redirect_to)
                else:
                    res['msg'] = '用户未激活！'
            else:
                res['msg'] = '用户名或密码错误！'
        else:
            res['msg'] = '用户和密码不能为空！'
        return render(request, 'system/login.html', res)


class LogoutView(View):

    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse('login'))




def mytest(request):
    return render(request, 'mytest.html')

templates/system/groups/group-edit.html
{% extends 'base-popup.html' %}
{% load staticfiles %}

{% block content %}
    <div class="ibox-content">
        <form class="form-horizontal" id="editForm" method="post">
            {% csrf_token %}
            <input type="hidden" name='id' value="{{ group.id }}"/>
            <legend style="overflow:hidden">
                <h4 style="width: 200px;float: left">{% if group.id %}编辑{% else %}新增{% endif %}角色信息</h4>
            </legend>
            <div class="form-group row">
                <label class="col-3 col-form-label">角色名称</label>
                <div class="col-8">
                    <input class="form-control" name="name" type="text" value="{{ group.name }}"/>
                </div>
            </div>
            <div class="hr-line-dashed"></div>
            <div class="form-group row">
                <div style="margin:0 auto">
                    <button type="button" id="btnCancel" class="btn btn-default margin-right ">重置</button>
                    <button type="button" id="btnSave" class="btn btn-info margin-right ">保存</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

{% block javascripts %}
    <script type="text/javascript">

        $("#btnSave").click(function () {
            var data = $("#editForm").serialize();
            $.ajax({
                type: $("#editForm").attr('method'),
                url: "{% url 'system:group-edit' %}",
                data: data,
                cache: false,
                success: function (msg) {
                    if (msg.result) {
                        swal({
                            title: "权限信息保存成功！",
                            type: "success",
                            confirmButtonText: "确定",
                        }, function () {
                            window.parent.location.reload();
                        });
                    } else {
                        swal({
                            title: "权限信息保存失败！",
                            type: "warning",
                            //showCancelButton: true,
                            confirmButtonColor: "#DD6B55",
                            confirmButtonText: "确定",
                            closeOnConfirm: false
                        });
                    }
                    return;
                }
            });
        });


        /*点取消刷新新页面*/
        $("#btnCancel").click(function () {
            window.location.reload();
        });
    </script>

{% endblock %}

templates/system/groups/group.html
{% extends "base-main.html" %}
{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/plugins/dataTables/jquery.datatables.min.css' %}">
    <link href="/static/css/plugins/sweetalert/sweetalert.css" rel="stylesheet">
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox ">
                <div class="ibox-title">
                    <h5>角色信息 &nbsp;</h5>
                    <button type="button" id="btnRefresh" class="btn btn-default">
                        <i class="glyphicon glyphicon-repeat"></i>刷新
                    </button>
                    <button type="button" id="btnCreate" class="btn btn-default">
                        <i class="glyphicon glyphicon-plus"></i>新增
                    </button>
                    <button type="button" id="btnDelete" class="btn btn-default">
                        <i class="glyphicon glyphicon-trash"></i>删除
                    </button>
                    <div class="ibox-tools">
                        <div class="form-inline">
                            搜索：<input type="text" id="select" name="select" size="15" class="input-mini">
                            <button type="button" id="selectClear" class="btn-default btn-mini"
                                    style="margin-right: 20px">
                                <i class="glyphicon glyphicon-refresh"></i>
                            </button>

                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="ibox-content">
                    <div class="table-responsive">
                        <table id="dblList" class="display table-striped table-bordered table-hover table-condensed"
                               cellspacing="0"
                               width="100%">
                            <thead>
                            <tr>
                                <th>
                                    <input type="checkbox" id="checkAll" class="group-checkable"
                                           style="margin-left: -8px"></th>
                                <th>编号</th>
                                <th>角色名称</th>
                                <th>操作</th>
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {{ request.menu_url_list }}
{% endblock %}
{% block javascripts %}

    <script src="/static/js/plugins/sweetalert/sweetalert.min.js"></script>
    <script src="{% static 'js/plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/plugins/datatables/dataTables.const.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            initTable();
        });

        function initTable() {
            //提示信息
            var lang = {
                "sProcessing": "处理中...",
                "sLengthMenu": "每页 _MENU_ 项",
                "sZeroRecords": "没有匹配结果",
                "sInfo": "当前显示第 _START_ 至 _END_ 项，共 _TOTAL_ 项。",
                "sInfoEmpty": "当前显示第 0 至 0 项，共 0 项",
                "sInfoFiltered": "(由 _MAX_ 项结果过滤)",
                "sInfoPostFix": "",
                "sSearch": "搜索:",
                "sUrl": "",
                "sEmptyTable": "表中数据为空",
                "sLoadingRecords": "载入中...",
                "sInfoThousands": ",",
                "oPaginate": {
                    "sFirst": "首页",
                    "sPrevious": "上页",
                    "sNext": "下页",
                    "sLast": "末页",
                    "sJump": "跳转"
                },
                "oAria": {
                    "sSortAscending": ": 以升序排列此列",
                    "sSortDescending": ": 以降序排列此列"
                }
            };
            $("#dblList").dataTable().fnDestroy();
            //初始化表格
            var table = $("#dblList").dataTable({
                lengthMenu: [20, 50, 100, 200],
                language: lang,  //提示信息
                autoWidth: false,  //禁用自动调整列宽
                stripeClasses: ["odd", "even"],  //为奇偶行加上样式，兼容不支持CSS伪类的场合
                processing: true,  //隐藏加载提示,自行处理
                serverSide: true,  //启用服务器端分页
                searching: false,  //禁用原生搜索
                orderMulti: false,  //启用多列排序
                order: [[1, "desc"]],  //取消默认排序查询,否则复选框一列会出现小箭头
                renderer: "bootstrap",  //渲染样式：Bootstrap和jquery-ui
                pagingType: "full_numbers",  //分页样式：simple,simple_numbers,full,full_numbers
                columnDefs: [{
                    "targets": 'nosort',  //列的样式名
                    "orderable": false    //包含上样式名‘nosort’的禁止排序
                }],
                ajax: function (data, callback, settings) {
                    //封装请求参数
                    var param = {};
                    param.limit = data.length;//页面显示记录条数，在页面显示每页显示多少项的时候
                    param.start = data.start;//开始的记录序号
                    param.page = (data.start / data.length) + 1;//当前页码
                    param.select = $("#select").val();
                    //console.log(data)
                    //ajax请求数据
                    $.ajax({
                        type: "GET",
                        url: "{% url 'system:group-list' %}",
                        cache: false,  //禁用缓存
                        data: param,  //传入组装的参数
                        dataType: "json",
                        success: function (result) {
                            //console.log(result);
                            //setTimeout仅为测试延迟效果
                            setTimeout(function () {
                                //封装返回数据
                                var returnData = {};
                                returnData.draw = data.draw;//这里直接自行返回了draw计数器,应该由后台返回
                                returnData.recordsTotal = result.total;//返回数据全部记录
                                returnData.recordsFiltered = result.total;//后台不实现过滤功能，每次查询均视作全部结果
                                returnData.data = result.data;//返回的数据列表
                                //console.log(returnData);
                                //调用DataTables提供的callback方法，代表数据已封装完成并传回DataTables进行渲染
                                //此时的数据需确保正确无误，异常判断应在执行此回调前自行处理完毕
                                callback(returnData);
                            }, 200);
                        }
                    });
                },
                //列表表头字段
                columns: [
                    DATATABLES_CONSTANT.DATA_TABLES.COLUMN.CHECKBOX,
                    {"data": "id", width: "10"},
                    {"data": "name"},
                    {
                        title: "操作",
                        data: "id",
                        width: "16%",
                        align: "right",
                        bSortable: false,
                        render:
                            function (data, type, row, meta) {
                                var ret = "<button title='详情-编辑' onclick='doUpdate("
                                    + data + ")'><i class='glyphicon glyphicon-pencil'></i></button>";
                                ret = ret + "<button title='关联用户' onclick='doUpdateUser("
                                    + data + ")'><i class='glyphicon glyphicon-user'></i></button>";
                                ret = ret + "<button title='关联菜单' onclick='doUpdateMenu("
                                    + data + ")'><i class='glyphicon glyphicon-tree-conifer'></i></button>";
                                ret = ret + "<button title='关联权限' onclick='doUpdatePermission("
                                    + data + ")'><i class='glyphicon glyphicon-asterisk'></i></button>";
                                ret = ret + "<button title='删除' onclick='doDelete("
                                    + data + ")'><i class='glyphicon glyphicon-trash'></i></button>";
                                return ret;
                            }
                    }
                ]
            }).api();
            //此处需调用api()方法,否则返回的是JQuery对象而不是DataTables的API对象
        }

        //新建按钮
        $("#btnCreate").click(function () {
            showPopup('增加角色信息',540,240,"{% url 'system:group-edit' %}");
        });

        // 跳转到详情页面
        function doUpdate(id) {
            showPopup('修改角色信息',540,240,"{% url 'system:group-edit' %}" + '?id=' + id);
        }

        //关联用户
        function doUpdateUser(id) {
            showPopup('关联教师信息',800,510,"{% url 'system:group-group2instructor' %}" + '?id=' + id);
        }

        //关联菜单
        function doUpdateMenu(id) {
            showPopup('关联菜单信息',800,510,"{% url 'system:group-group2menu' %}" + '?id=' + id);
        }

        //关联权限
        function doUpdatePermission(id) {
            showPopup('关联权限信息',800,510,"{% url 'system:group-group2permission' %}" + '?id=' + id);
        }

        //刷新按钮
        $("#btnRefresh").click(function () {
            initTable();
        });

        $("#select").change(function () {
            initTable();
        });

        $("#selectClear").click(function () {
            $("#select").val('');
            initTable();
        });

        //删除单个教师
        function doDelete(id) {
            deleteData("{% url 'system:group-delete' %}", "{{ csrf_token }}", initTable, id);
        }

        //批量删除
        $("#btnDelete").click(function () {
            deleteData("{% url 'system:group-delete' %}", "{{ csrf_token }}", initTable);
        });
    </script>
{% endblock %}

templates/system/groups/group2instructor.html
{% extends "base-popup.html" %}
{% load staticfiles %}
{% block css %}
    <link href="{% static 'css/plugins/dualListbox/bootstrap-duallistbox.min.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
    <div class="ibox-content">
        <form class="form-horizontal" id="selectInstructorsForm" action="" method="post">
            {% csrf_token %}
            <input type="hidden" name='id' value="{{ group.id }}"/>
            <legend style="overflow:hidden">
                <h4 style="float: left">关联教师：{{ group.name }}
                    <small>一个教师可以隶属多个角色</small>
                </h4>
            </legend>
            <div class="row">
                <div class="col-12 margin-top-5">
                    <form id="form" action="#" class="wizard-big">
                        <select class="form-control dual_select" multiple id="selInstructors" name="selInstructors">
                            {% for item in un_add_instructors %}
                                <option value="{{ item.id }}">{{ item.name }}({{ item.username }}) -- [{{ item.department.name|default:"无部门" }}]</option>
                            {% endfor %}
                            {% for item in added_instructors %}
                                <option selected value="{{ item.id }}">{{ item.name }}({{ item.username }}) -- [{{ item.department.name }}]</option>
                            {% endfor %}
                        </select>
                    </form>
                </div>
            </div>
            <div class="hr-line-dashed"></div>
            <div class="form-group row">
                <div style="margin:0 auto">
                    <button type="button" id="btnCancel" class="btn btn-default margin-right ">重置</button>
                    <button type="button" id="btnSave" class="btn btn-info margin-right ">保存</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

{% block javascripts %}
    <script src="{% static 'js/plugins/dualListbox/jquery.bootstrap-duallistbox.js' %}"></script>
    <script type="text/javascript">
        var selectorx = $('.dual_select').bootstrapDualListbox({
            selectorMinimalHeight: 230,
            nonSelectedListLabel: '',//未选项
            selectedListLabel: '',//已选项
            filterTextClear: '全部',
            filterPlaceHolder: '过滤条件',
            preserveSelectionOnMove: 'moved',
            //moveOnSelect: false,
            moveAllLabel: '添加全部',
            moveSelectedLabel: '添加选中',
            removeAllLabel: '移除全部',
            removeSelectedLabel: '移除选中',
            infoText: '选中/未选中共 {0} 项',
            infoTextFiltered: '从 {1} 项 筛选 {0} 项',
            infoTextEmpty: '空'
        });

        $("#btnSave").click(function () {
            var data = $("#selectInstructorsForm").serialize();
            $.ajax({
                type: "post",
                url: "{% url 'system:group-group2instructor' %}",
                data: data,
                cache: false,
                success: function (msg) {
                    if (msg.result) {
                        swal({
                            title: "操作成功",
                            type: "success",
                            confirmButtonText: "确定"
                        }, function () {
                            parent.closePopup('#popup-div');
                        });
                    } else {
                        swal({
                            title: "操作失败",
                            type: "warning",
                            //showCancelButton: true,
                            confirmButtonColor: "#DD6B55",
                            confirmButtonText: "确定",
                            closeOnConfirm: false
                        });
                    }
                    return;
                }
            });
        });

        /*点取消刷新新页面*/
        $("#btnCancel").click(function () {
            window.location.reload();
        });
    </script>
{% endblock %}