SchoolOABase/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.views.static import serve
from system.views import IndexView, LoginView, LogoutView, mytest
from tools import views as tools_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='temp-index'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('system/', include('system.urls')),
    path('base/', include('base.urls', namespace='base')),
    path('attendance/', include('attendance.urls', namespace='attendance')),

    path('mytest/', mytest),

]
urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {"document_root": settings.MEDIA_ROOT}),
]

apps/attendance/urls.py
# -*- coding: utf-8 -*-
"""
@File    : urls.py
@Time    : 2019-08-30 16:09
@Author  : 杨小林
"""
from django.urls import path
from . import views, views_nocheckin, views_leave, views_overtime, views_outwork

app_name = 'attendance'

urlpatterns = [
    path('nocheckin/', views_nocheckin.NoCheckInView.as_view(), name='nocheckin'),
    path('nocheckin/list/', views_nocheckin.NoCheckInListView.as_view(), name='nocheckin-list'),
    path('nocheckin/apply/', views_nocheckin.NoCheckInApplyView.as_view(), name='nocheckin-apply'),
    path('nocheckin/process/', views_nocheckin.NoCheckInProcessView.as_view(), name='nocheckin-process'),
    path('nocheckin/delete/', views_nocheckin.NoCheckInDeleteView.as_view(), name='nocheckin-nocheckin'),

    path('leave/', views_leave.LeaveView.as_view(), name='leave'),
    path('leave/list/', views_leave.LeaveListView.as_view(), name='leave-list'),
    path('leave/apply/', views_leave.LeaveApplyView.as_view(), name='leave-apply'),
    path('leave/process/', views_leave.LeaveProcessView.as_view(), name='leave-process'),
    path('leave/delete/', views_leave.LeaveDeleteView.as_view(), name='leave-delete'),

    path('overtime/', views_overtime.OverTimeView.as_view(), name='overtime'),
    path('overtime/list/', views_overtime.OverTimeListView.as_view(), name='overtime-list'),
    path('overtime/apply/', views_overtime.OverTimeApplyView.as_view(), name='overtime-apply'),
    path('overtime/process/', views_overtime.OverTimeProcessView.as_view(), name='overtime-process'),
    path('overtime/delete/', views_overtime.OverTimeDeleteView.as_view(), name='overtime-delete'),

    path('outwork/', views_outwork.OutWorkView.as_view(), name='outwork'),
    path('outwork/list/', views_outwork.OutWorkListView.as_view(), name='outwork-list'),
    path('outwork/apply/', views_outwork.OutWorkApplyView.as_view(), name='outwork-apply'),
    path('outwork/process/', views_outwork.OutWorkProcessView.as_view(), name='outwork-process'),
    path('outwork/delete/', views_outwork.OutWorkDeleteView.as_view(), name='outwork-delete'),

]

apps/attendance/models.py
import datetime, time
from django.utils.timezone import now
from django.db import models
from django.contrib.auth import get_user_model

Instructor = get_user_model()

check_in_period_choices = ((1, '上午上班'), (2, '上午下班'), (3, '下午上班'), (4, '下午下班'))
step_choices = ((1, '提出申请'), (2, '部门主管处理'), (3, '校区主任处理'), (4, '审批完毕'))
result_choices = ((0, '处理中...'), (1, '同意'), (2, '不同意'))
is_agree_choices = ((0, '未审核'), (1, '同意'), (2, '不同意'))
leave_type_choice = ((1, '病假'), (2, '事假'), (3, '婚假'), (4, '产假'), (5, '父亲假'), (6, '工伤假'), (7, '丧假'), (8, '调休'))
module_choices = ((1, '缺打卡'), (2, '请假'), (3, '加班'), (4, '外勤'), (5, '出差'), (6, '调休'))


class NoCheckIn(models.Model):
    """
    忘打卡申请
    """
    applicant = models.ForeignKey(Instructor, on_delete=models.CASCADE, verbose_name='申请人',
                                  related_name='no_check_in_applyer')
    missing_time = models.DateTimeField(verbose_name='缺打卡时间')
    check_in_period = models.IntegerField(choices=check_in_period_choices, verbose_name='打卡时段')
    reason = models.CharField(max_length=256, verbose_name='缺打卡原因')
    witness = models.CharField(max_length=256, verbose_name="缺打卡事由")
    auditor = models.ForeignKey(Instructor, null=True, on_delete=models.CASCADE,
                                related_name='no_check_in_auditor', verbose_name='应审核人')
    step = models.IntegerField(choices=step_choices, verbose_name='处理步骤')
    result = models.IntegerField(choices=result_choices, verbose_name='审核结果')
    crdate = models.DateTimeField(default=now, verbose_name='创建时间')

    def __str__(self):
        return self.applicant.name

    class Meta:
        verbose_name = '缺打卡申请'
        verbose_name_plural = verbose_name

        permissions = (
            ("process_nocheckin", "行政人事.考勤管理.缺打卡.处理申请"),
            ("view_all_nocheckin", "行政人事.考勤管理.缺打卡.查看所有申请"),
            ("view_deprtment_nocheckin", "行政人事.考勤管理.缺打卡.查看本部门申请"),
        )


class AttendanceLog(models.Model):
    """
    考勤相关模块操作记录
    """
    module_id = models.IntegerField(choices=module_choices, verbose_name='模块ID')
    relate_id = models.IntegerField(null=False, verbose_name='关联申请ID')
    auditor = models.ForeignKey(Instructor, null=True, on_delete=models.SET_NULL, verbose_name='审批人')
    step = models.CharField(max_length=2, choices=step_choices, verbose_name='步骤')
    view_time = models.DateTimeField(null=True, verbose_name='查看时间')
    process_time = models.DateTimeField(null=True, verbose_name='处理时间')
    is_agree = models.IntegerField(null=True, choices=is_agree_choices, verbose_name='是否同意')
    opinion = models.CharField(max_length=256, null=True, verbose_name='审核意见')
    crdate = models.DateTimeField(default=now, verbose_name='创建时间')


class Leave(models.Model):
    """
    请假申请
    """
    applicant = models.ForeignKey(Instructor, on_delete=models.CASCADE, verbose_name='申请人',
                                  related_name='leave_applicant')
    start_time = models.DateTimeField(verbose_name='开始时间')
    end_time = models.DateTimeField(verbose_name='结束时间')
    leave_hours = models.DecimalField(max_digits=5, decimal_places=1, null=True, verbose_name='请假时长')
    leave_type = models.IntegerField(choices=leave_type_choice, verbose_name='请假类型')
    reason = models.CharField(max_length=256, verbose_name="请假原因")
    auditor = models.ForeignKey(Instructor, null=True, on_delete=models.CASCADE, verbose_name='审核人',
                                related_name='leave_auditor')
    step = models.IntegerField(choices=step_choices, verbose_name='处理步骤')
    result = models.IntegerField(choices=result_choices, verbose_name='审核结果')
    crdate = models.DateTimeField(default=now, verbose_name='创建时间')

    def __str__(self):
        return self.applicant.name

    class Meta:
        verbose_name = '请假申请'
        verbose_name_plural = verbose_name

        permissions = (
            ("process_leave", "行政人事.考勤管理.请假.处理申请"),
            ("view_all_leave", "行政人事.考勤管理.请假.查看所有申请"),
            ("view_deprtment_leave", "行政人事.考勤管理.请假.查看本部门申请"),
        )


class OverTime(models.Model):
    """
    请假申请
    """
    applicant = models.ForeignKey(Instructor, on_delete=models.CASCADE, verbose_name='申请人',
                                  related_name='overtime_applicant')
    start_time = models.DateTimeField(verbose_name='开始时间')
    end_time = models.DateTimeField(verbose_name='结束时间')
    overtime_hours = models.DecimalField(max_digits=5, decimal_places=1, null=True, verbose_name='加班时长')
    reason = models.CharField(max_length=256, verbose_name="加班原因")
    auditor = models.ForeignKey(Instructor, null=True, on_delete=models.CASCADE, verbose_name='审核人',
                                related_name='overtime_auditor')
    step = models.IntegerField(choices=step_choices, verbose_name='处理步骤')
    result = models.IntegerField(choices=result_choices, verbose_name='审核结果')
    crdate = models.DateTimeField(default=now, verbose_name='创建时间')

    def __str__(self):
        return self.applicant.name

    class Meta:
        verbose_name = '加班申请'
        verbose_name_plural = verbose_name

        permissions = (
            ("process_overtime", "行政人事.考勤管理.加班.处理申请"),
            ("view_all_overtime", "行政人事.考勤管理.加班.查看所有申请"),
            ("view_deprtment_overtime", "行政人事.考勤管理.加班.查看本部门申请"),
        )


class OutWork(models.Model):
    """
    请假申请
    """
    applicant = models.ForeignKey(Instructor, on_delete=models.CASCADE, verbose_name='申请人',
                                  related_name='outwork_applicant')
    start_time = models.DateTimeField(verbose_name='开始时间')
    end_time = models.DateTimeField(verbose_name='结束时间')
    outwork_hours = models.DecimalField(max_digits=5, decimal_places=1, null=True, verbose_name='外勤时长')
    address = models.CharField(max_length=256, verbose_name='外勤地点')
    reason = models.CharField(max_length=256, verbose_name="外勤原因")
    auditor = models.ForeignKey(Instructor, null=True, on_delete=models.CASCADE, verbose_name='审核人',
                                related_name='outwork_auditor')
    step = models.IntegerField(choices=step_choices, verbose_name='处理步骤')
    result = models.IntegerField(choices=result_choices, verbose_name='审核结果')
    crdate = models.DateTimeField(default=now, verbose_name='创建时间')

    def __str__(self):
        return self.applicant.name

    class Meta:
        verbose_name = '外勤申请'
        verbose_name_plural = verbose_name

        permissions = (
            ("process_outwork", "行政人事.考勤管理.外勤.处理申请"),
            ("view_all_outwork", "行政人事.考勤管理.外勤.查看所有申请"),
            ("view_deprtment_outwork", "行政人事.考勤管理.外勤.查看本部门申请"),
        )


class BusinessTrip(models.Model):
    """
    出差申请
    """
    applicant = models.ForeignKey(Instructor, on_delete=models.CASCADE, verbose_name='申请人',
                                  related_name='businesstrip_applicant')
    start_time = models.DateTimeField(verbose_name='开始时间')
    end_time = models.DateTimeField(verbose_name='结束时间')
    destination = models.CharField(max_length=256, verbose_name='目的地')
    reason = models.CharField(max_length=256, verbose_name="出差原因")
    expected_result = models.CharField(max_length=512, verbose_name="预计归来的结果")
    required_support = models.CharField(max_length=512, verbose_name="所需支持")
    auditor = models.ForeignKey(Instructor, null=True, on_delete=models.CASCADE, verbose_name='审核人',
                                related_name='businesstrip_auditor')
    step = models.IntegerField(choices=step_choices, verbose_name='处理步骤')
    result = models.IntegerField(choices=result_choices, verbose_name='审核结果')
    crdate = models.DateTimeField(default=now, verbose_name='创建时间')

    def __str__(self):
        return self.applicant.name

    class Meta:
        verbose_name = '出差申请'
        verbose_name_plural = verbose_name

        permissions = (
            ("process_businesstrip", "行政人事.考勤管理.出差.处理申请"),
            ("view_all_businesstrip", "行政人事.考勤管理.出差.查看所有申请"),
            ("view_deprtment_businesstrip", "行政人事.考勤管理.出差.查看本部门申请"),
        )


class BreakOff(models.Model):
    """
    调休申请
    """
    applicant = models.ForeignKey(Instructor, on_delete=models.CASCADE, verbose_name='申请人',
                                  related_name='breakoff_applicant')
    start_time = models.DateTimeField(verbose_name='开始时间')
    end_time = models.DateTimeField(verbose_name='结束时间')
    breakoff_hours = models.DecimalField(max_digits=5, decimal_places=1, null=True, verbose_name='调休时长')
    reason = models.CharField(max_length=256, verbose_name="调休原因")
    auditor = models.ForeignKey(Instructor, null=True, on_delete=models.CASCADE, verbose_name='审核人',
                                related_name='breakoff_auditor')
    step = models.IntegerField(choices=step_choices, verbose_name='处理步骤')
    result = models.IntegerField(choices=result_choices, verbose_name='审核结果')
    crdate = models.DateTimeField(default=now, verbose_name='创建时间')

    def __str__(self):
        return self.applicant.name

    class Meta:
        verbose_name = '调休申请'
        verbose_name_plural = verbose_name

        permissions = (
            ("process_breakoff", "行政人事.考勤管理.调休.处理申请"),
            ("view_all_breakoff", "行政人事.考勤管理.调休.查看所有申请"),
            ("view_deprtment_breakoff", "行政人事.考勤管理.调休.查看本部门申请"),
        )


class Vacation(models.Model):
    '''假期信息'''

    instructor = models.ForeignKey(Instructor, on_delete=models.CASCADE, verbose_name='员工',
                                   related_name='vacation_instructor')
    remaining_time = models.DecimalField(max_digits=5, decimal_places=1, null=True, verbose_name='剩余调休时长')
    adjust_time = models.DecimalField(max_digits=5, decimal_places=1, null=True, verbose_name='本次调整时长')
    auditor = models.ForeignKey(Instructor, on_delete=models.CASCADE, verbose_name='审核人',
                                related_name='vacation_auditor')
    adjust_reason = models.CharField(max_length=256, verbose_name='调整原因')
    crdate = models.DateTimeField(default=now, verbose_name='创建时间')

    def __str__(self):

apps/attendance/forms.py
# -*- coding: utf-8 -*-
"""
@File    : forms.py
@Time    : 2019-09-01 19:46
@Author  : 杨小林
"""
import re
from django import forms
from . import models
from datetime import datetime


class NoCheckInApplyForm(forms.ModelForm):
    class Meta:
        model = models.NoCheckIn
        fields = ['missing_time', 'check_in_period', 'reason', 'witness',
                  'auditor', 'step', 'result', 'applicant'
                  ]

        error_messages = {
            "missing_time": {"required": "缺打卡时间不能为空"},
            "check_in_period": {"required": "缺打卡时段不能为空"},
            "reason": {"required": "缺打卡原因不能为空"},
            "witness": {"required": "缺打卡事由不能为空"}
        }


class LeaveApplyForm(forms.ModelForm):
    class Meta:
        model = models.Leave
        fields = '__all__'

        error_messages = {
            'start_time': {'required': '开始时间不能为空'},
            'end_time': {'required': '结束时间不能为空'},
            'leave_type': {'required': '请假类型不能为空'},
            'reason': {'required': '请假原因不能为空'}
        }

    def clean(self):
        cleaned_data = super(LeaveApplyForm, self).clean()
        start_time = cleaned_data.get("start_time")
        end_time = cleaned_data.get("end_time")
        reason = cleaned_data.get("reason", "")
        leave_type = cleaned_data.get("leave_type")
        leave_hours = cleaned_data.get("leave_hours")
        crdate = datetime.now()

        if start_time > end_time:
            raise forms.ValidationError("结束时间必须晚于开始时间")


class OverTimeApplyForm(forms.ModelForm):
    class Meta:
        model = models.OverTime
        fields = '__all__'

        error_messages = {
            'start_time': {'required': '开始时间不能为空'},
            'end_time': {'required': '结束时间不能为空'},
            'overtime_type': {'required': '请假类型不能为空'},
            'reason': {'required': '请假原因不能为空'}
        }

    def clean(self):
        cleaned_data = super(OverTimeApplyForm, self).clean()
        start_time = cleaned_data.get("start_time")
        end_time = cleaned_data.get("end_time")
        reason = cleaned_data.get("reason", "")
        overtime_hours = cleaned_data.get("overtime_hours")
        crdate = datetime.now()

        if start_time > end_time:
            raise forms.ValidationError("结束时间必须晚于开始时间")


class OutWorkApplyForm(forms.ModelForm):
    class Meta:
        model = models.OutWork
        fields = '__all__'

        error_messages = {
            'start_time': {'required': '开始时间不能为空'},
            'end_time': {'required': '结束时间不能为空'},
            'address': {'required': '外勤地点不能为空'},
            'reason': {'required': '外勤原因不能为空'}
        }

    def clean(self):
        cleaned_data = super(OutWorkApplyForm, self).clean()
        start_time = cleaned_data.get("start_time")
        end_time = cleaned_data.get("end_time")
        reason = cleaned_data.get("reason", "")
        address = cleaned_data.get("address", "")
        outwork_hours = cleaned_data.get("outwork_hours")
        crdate = datetime.now()

        if start_time > end_time:
            raise forms.ValidationError("结束时间必须晚于开始时间")

apps/attendance/views.py
from django.shortcuts import render
from django.views.generic import View


class H1View(View):

    def get(self, request):
        return render(request, 'attendance/h1.html')


class H2View(View):

    def get(self, request):
        return render(request, 'attendance/h2.html')

class OutWorkView(View):

    def get(self, request):
        return render(request, 'attendance/outwork.html')

templates/attendance/nocheckins/nocheckin-apply.html
<div class="form-group row">
    <label class="col-2 col-form-label">缺打卡时间</label>
    <div class="col-3">
        <input class="form-control" type="text" name="missing_time" placeholder="例:2019-1-1 12:00"/>
    </div>
    <label class="col-2 col-form-label">缺打卡时段</label>
    <div class="col-3">
        <select class="form-control" name="check_in_period">
            <option>--请选择时段--</option>
            <option value="1">上午上班</option>
            <option value="2">上午下班</option>
            <option value="3">下午上班</option>
            <option value="4">下午下班</option>
        </select>
    </div>
</div>
<div class="form-group row">
    <label class="col-2 col-form-label">缺打卡原因</label>
    <div class="col-8">
        <textarea class="form-control" name="reason" rows="3"></textarea>
    </div>
</div>
<div class="form-group row">
    <label class="col-2 col-form-label">缺打卡事由</label>
    <div class="col-8">
        <textarea class="form-control" name="witness" rows="3"></textarea>
    </div>
</div>

templates/attendance/nocheckins/nocheckin-process.html
<div class="form-group row">
    <label class="col-2 col-form-label">缺打卡时间</label>
    <div class="col-3">
        <input class="form-control" type="text" value="{{ data.missing_time }}"/>
    </div>
    <label class="col-2 col-form-label">缺打卡时段</label>
    <div class="col-3">
        <input class="form-control" type="text"
               value="{% for item in check_in_period %}{% if item.0 == data.check_in_period %}{{ item.1 }}{% endif %}{% endfor %}"/>
    </div>
</div>
<div class="form-group row">
    <label class="col-2 col-form-label">缺打卡原因</label>
    <div class="col-8">
        <textarea class="form-control">{{ data.reason }}</textarea>
    </div>
</div>
<div class="form-group row">
    <label class="col-2 col-form-label">缺打卡事由</label>
    <div class="col-8">
        <textarea class="form-control">{{ data.witness }}</textarea>
    </div>
</div>

templates/attendance/nocheckins/nocheckin.html
{% extends "base-main.html" %}
{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/plugins/dataTables/jquery.datatables.min.css' %}">
    <link href="/static/css/plugins/sweetalert/sweetalert.css" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox ">
                <div class="ibox-title">
                    <h5>缺打卡信息 &nbsp;</h5>
                    <button type="button" id="btnRefresh" class="btn btn-default">
                        <i class="glyphicon glyphicon-repeat"></i>刷新
                    </button>
                    <button type="button" id="btnApply" class="btn btn-default">
                        <i class="glyphicon glyphicon-plus"></i>申请
                    </button>
                    <div class="ibox-tools">
                        <form class="form-inline">
                            <div class="form-group">
                                <select id="sel_month" name="select" class="form-control">
                                    <option style='text-align:center' value=''>--请选择月份--</option>
                                    {% for item in months %}
                                        <option value="{{ item }}">{{ item }}</option>
                                    {% endfor %}
                                </select>
                                <select id="sel_dept" name="select" class="form-control">
                                    <option style='text-align:center' value=''>--请选择部门--</option>
                                    {% for item in departments %}
                                        <option value="{{ item.id }}">{{ item.name }}</option>
                                    {% endfor %}
                                </select>
                                <select id="sel_user" name="select" class="form-control">
                                    <option style='text-align:center' value=''>--请选择员工--</option>
                                    {% for item in instructs %}
                                        <option value="{{ item.id }}">{{ item.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                        </form>
                    </div>
                </div>
                <div class="ibox-content">
                    <div class="table-responsive">
                        <table id="dtbList" class="display table-striped table-bordered table-hover table-condensed"
                               style="width:100%">
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script src="/static/js/plugins/sweetalert/sweetalert.min.js"></script>
    <script src="{% static 'js/plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/plugins/datatables/dataTables.const.js' %}"></script>
    <script>
        //显示数据表格
        var oDataTable = null;
        $(function () {
            oDataTable = initTable();
        });

        //显示列表
        function initTable() {
            var oTable = $('#dtbList').DataTable({
                "paging": true,
                "pagingType": "full_numbers",
                "lengthMenu": [20, 50, 100, 200],
                "processing": true,
                "searching": true, //是否开启搜索
                //"serverSide": true,//开启服务器获取数据
                "order": [[1, "desc"]], //默认排序
                ajax: {
                    "url": "{% url 'attendance:nocheckin-list' %}?month=" + $('#sel_month').val() + '&dept=' + $('#sel_dept').val() + '&user=' + $('#sel_user').val(),
                    "data": function (d) {
                        d.select = $("#select").val();
                    }
                },
                columns: [
                    {"title": "ID", "data": "id", "width": "6%"},
                    {"title": "申请人", "data": "applicant__name",},
                    {"title": "缺打卡时间", "data": "missing_time"},
                    {"title": "打卡时段", "data": "check_in_period"},
                    {"title": "缺打卡原因", "data": "reason", width: '20%'},
                    {"title": "缺打卡事由", "data": "witness", width: '20%'},
                    {"title": "当前步骤", "data": "cur_step"},
                    {"title": "处理人", "data": "cur_processer__name"},
                    {"title": "申请结果", "data": "result"},
                    {
                        title: "操作",
                        data: "id",
                        width: "8%",
                        align: "right",
                        bSortable: false,
                        render:
                            function (data, type, row, meta) {
                                var ret = "<button title='详情-处理' onclick='doUpdate("
                                    + data + ")'><i class='glyphicon glyphicon-pencil'></i></button>";
                                return ret;
                            }
                    }
                ],
                "language":
                    { // 定义语言
                        "sProcessing":
                            "加载中...",
                        "sLengthMenu":
                            "每页显示 _MENU_ 条记录",
                        "sZeroRecords":
                            "没有匹配的结果",
                        "sInfo":
                            "显示第 _START_ 至 _END_ 项结果，共 _TOTAL_ 项",
                        "sInfoEmpty":
                            "显示第 0 至 0 项结果，共 0 项",
                        "sInfoFiltered":
                            "(由 _MAX_ 项结果过滤)",
                        "sInfoPostFix":
                            "",
                        "sSearch":
                            "搜索:",
                        "sUrl":
                            "",
                        "sEmptyTable":
                            "表中数据为空",
                        "sLoadingRecords":
                            "载入中...",
                        "sInfoThousands":
                            ",",
                        "oPaginate":
                            {
                                "sFirst":
                                    "首页 ",
                                "sPrevious":
                                    "上一页 ",
                                "sNext":
                                    "下一页 ",
                                "sLast":
                                    "末页"
                            }
                        ,
                        "oAria":
                            {
                                "sSortAscending":
                                    ": 以升序排列此列",
                                "sSortDescending":
                                    ": 以降序排列此列"
                            }
                    },
            });

            return oTable;
        }


        //刷新按钮
        $("#btnRefresh").click(function () {
            window.location.reload();
        });

        //新建按钮
        $("#btnApply").click(function () {
            showPopup('缺打卡申请', 840, 450, "{% url 'attendance:nocheckin-apply' %}");
        });

        // 跳转到教师详情页面
        function doUpdate(id) {
            showPopup('缺打卡申请--处理', 840, 540, "{% url 'attendance:nocheckin-process' %}" + '?id=' + id);
        }

        $("#sel_month").change(function () {
            doRefresh()
        });
        $("#sel_dept").change(function () {
            doRefresh()
        });
        $("#sel_user").change(function () {
            doRefresh()
        });

        function doRefresh() {
            $("#dtbList").dataTable().fnDestroy();
            oDataTable = initTable();
        }
    </script>
{% endblock %}