SchoolOABase/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.views.static import serve
from system.views import IndexView, LoginView, LogoutView, mytest
from tools import views as tools_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='temp-index'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('system/', include('system.urls')),
    path('base/', include('base.urls', namespace='base')),
    path('attendance/', include('attendance.urls', namespace='attendance')),

    path('mytest/', mytest),

]
urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {"document_root": settings.MEDIA_ROOT}),
]

apps/system/urls.py
from django.urls import path
from . import views, views_instructor, views_menu, views_permission, views_group, views_home

app_name = 'system'
urlpatterns = [
    path('home/profile/', views_home.InstructorProfileView.as_view(), name='home-profile'),
    path('home/login_pwd_change/', views_home.LoginPwdChangeView.as_view(), name='home-login_pwd_change'),
    path('home/private_pwd_change/', views_home.PrivatePwdChangeView.as_view(), name='home-private_pwd_change'),

    path('', views.IndexView.as_view(), name='system-index'),
    path('instructor/', views_instructor.InstructorView.as_view(), name='instructor'),
    path('instructor/list/', views_instructor.InstructorListView.as_view(), name='instructor-list'),
    path('instructor/create/', views_instructor.InstructorCreateView.as_view(), name='instructor-create'),
    path('instructor/update/', views_instructor.InstructorUpdateView.as_view(), name='instructor-update'),
    path('instructor/password_change/', views_instructor.PasswordChangeView.as_view(),
         name='instructor-password-change'),
    path('instructor/delete/', views_instructor.InstructorDeleteView.as_view(), name='instructor-delete'),
    path('instructor/enable/', views_instructor.InstructorEnableView.as_view(), name='instructor-enable'),
    path('instructor/disable/', views_instructor.InstructorDisableView.as_view(), name='instructor-disable'),

    path('menu/', views_menu.MenuView.as_view(), name='menu'),
    path('menu/edit/', views_menu.MenuEditView.as_view(), name='menu-edit'),
    path('menu/delete/', views_menu.MenuDeleteView.as_view(), name='menu-delete'),
    path('menu/list/', views_menu.MenuListView.as_view(), name='menu-list'),

    path('permission/', views_permission.PermissionView.as_view(), name='permission'),
    path('permission/edit/', views_permission.PermissionEditView.as_view(), name='permission-edit'),
    path('permission/delete/', views_permission.PermissionDeleteView.as_view(), name='permission-delete'),
    path('permission/list/', views_permission.PermissionListView.as_view(), name='permission-list'),

    path('group/', views_group.GroupView.as_view(), name='group'),
    path('group/edit/', views_group.GroupEditView.as_view(), name='group-edit'),
    path('group/delete/', views_group.GroupDeleteView.as_view(), name='group-delete'),
    path('group/list/', views_group.GroupListView.as_view(), name='group-list'),
    path('group/group2instructor/', views_group.Group2InstructorView.as_view(), name="group-group2instructor"),
    path('group/group2menu/', views_group.Group2MenuView.as_view(), name="group-group2menu"),
    path('group/group2menu_list/', views_group.Group2MenuListView.as_view(), name="group-group2menu_list"),
    path('group/group2permission/', views_group.Group2PermissionView.as_view(), name="group-group2permission"),
    # path('demo/', views.demo, name='system-demo'),
    # path('demoview1/', permission_required('base.add_department')(views.DemoView.as_view()), name='viewAssetHistory'),
    # path('demoview2/', permission_required('base.change_department')(views.DemoView.as_view()),
    #     name='viewAssetHistory'),
]

apps/system/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, AbstractBaseUser
from django.contrib.auth.models import Group, Permission


class Menu(models.Model):
    """
    菜单
    """
    name = models.CharField(max_length=30, unique=True, verbose_name='菜单名')
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.SET_NULL, verbose_name='父菜单')
    icon = models.CharField(max_length=50, null=True, blank=True, verbose_name='图标')
    url = models.CharField(max_length=128, null=True, blank=True, verbose_name='链接')
    number = models.CharField(max_length=20, null=True, blank=True, verbose_name="编号")
    # code = models.CharField(max_length=30, unique=True, default='', verbose_name='编码')
    groups = models.ManyToManyField(to=Group, verbose_name="角色")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '菜单'
        verbose_name_plural = verbose_name
        ordering = ['number']

    @classmethod
    def get_menu_by_request(cls, url):
        return dict(menu=Menu.objects.get(url=url))

    @classmethod
    def get_menu_by_request_url(cls, url):
        try:
            return dict(menu=Menu.objects.get(url=url))
        except:
            return None


class Instructor(AbstractUser):
    '''
    用户
    '''
    name = models.CharField(max_length=20, default='', verbose_name='姓名')
    gender = models.CharField(max_length=2, choices=(('男', '男'), ('女', '女')), default='男', verbose_name='性别')
    mobile = models.CharField(max_length=11, unique=True, default='', verbose_name='手机号')
    email = models.EmailField(max_length=30, verbose_name='邮箱')
    birthday = models.DateField(null=True, blank=True, verbose_name='出生日期')
    headimage = models.ImageField(upload_to='images/instructor/headimage', default='images/default.jpg', max_length=100,
                                  null=True, blank=True, verbose_name='头像')
    department = models.ForeignKey('base.Department', null=True, blank=True, on_delete=models.SET_NULL,
                                   verbose_name='部门')
    post = models.CharField(max_length=50, null=True, blank=True, verbose_name='职位')
    is_manager = models.BooleanField(default=False, verbose_name='是部门经理')
    superior = models.ForeignKey('self', null=True, blank=True, on_delete=models.SET_NULL, verbose_name='上级主管')
    private_password = models.CharField(max_length=128, null=True, verbose_name='私有密码')

    class Meta:
        verbose_name = '教师'
        verbose_name_plural = verbose_name
        ordering = ['id']

        permissions = (
            ("change_password", "基础数据.教师.修改密码"),
            ("enable_user", "基础数据.教师.启用用户"),
            ("disable_user", "基础数据.教师.禁用用户"),
        )

    def __str__(self):
        return self.name + ' ' + self.gender + ' '  # + self.department.name + self.mobile + ' ' + self.email

templates/base-main.html
{% extends "left-right.html" %}
{% load staticfiles %}

{% block menu %}
    {{ request.session.my_menu_string |safe }}
{% endblock %}
{% block content %}
{% endblock %}
{% block menuscripts %}
    <script type="text/javascript">
        menu_list ={{ request.session.tree_menus|safe }}
    </script>
{% endblock %}

templates/base-popup.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>美和易思&bull;莱芜School OA | 主页</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/font-awesome/css/font-awesome.css" rel="stylesheet">
    <link href="/static/css/plugins/iCheck/custom.css" rel="stylesheet">
    <link href="/static/css/animate.css" rel="stylesheet">
    <link href="/static/css/style.css" rel="stylesheet">
    <link href="/static/css/plugins/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css" rel="stylesheet">
    <link href="/static/css/plugins/sweetalert/sweetalert.css" rel="stylesheet">
    {% block css %}
    {% endblock %}
    <style type="text/css">
        label {
            text-align: right
        }

        .i-checks {
            padding-top: 5px;
            padding-left: 10px
        }

        h4 {
            margin: 10px 0;
            line-height: 1.1;
        }

        legend {
            display: block;
            width: 100%;
            padding: 0;
            margin-bottom: 20px;
            line-height: inherit;
            color: #333;
            border: 0;
            border-bottom: 1px solid #e5e5e5;
            padding-inline-start: 2px;
            padding-inline-end: 2px;
        }
    </style>
</head>
<body style="background-color: white">
<div class="fadeInRight"><!--animated-->
    <div class="row">
        <div class="col-lg-12">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>
<!-- Mainly scripts -->
<script src="/static/js/jquery-3.1.1.min.js"></script>
<script src="/static/js/popper.min.js"></script>
<script src="/static/js/bootstrap.js"></script>
<script src="/static/js/plugins/metisMenu/jquery.metisMenu.js"></script>
<script src="/static/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>
<!-- Custom and plugin javascript -->
<script src="/static/js/inspinia.js"></script>
<script src="/static/js/plugins/pace/pace.min.js"></script>
<!-- iCheck -->
<script src="/static/js/plugins/iCheck/icheck.min.js"></script>
<script src="/static/js/plugins/sweetalert/sweetalert.min.js"></script>

<script>
    $(document).ready(function () {
        $('.i-checks').iCheck({
            checkboxClass: 'icheckbox_square-green',
            radioClass: 'iradio_square-green',
        });
    });

    function doSave(form, doUrl, success_title, success_action) {
        var data = $("#" + form).serialize();
        $.ajax({
            type: $("#" + form).attr('method'),
            url: doUrl,
            data: data,
            cache: false,
            success: function (msg) {
                if (msg.result) {
                    swal({
                        title: success_title,
                        type: "success",
                        confirmButtonText: "确定",
                    }, function () {
                        if (success_action == 1)
                            window.parent.location.reload();
                    });
                } else {
                    swal({
                        title: msg.error_messages,
                        type: "warning",
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "确定",
                        closeOnConfirm: false
                    });
                }
                return;
            }
        });
    }
</script>
{% block javascripts %}
{% endblock %}
</body>
</html>

templates/base-static.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>美和易思&bull;莱芜School OA | 主页</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'font-awesome/css/font-awesome.css' %}" rel="stylesheet">
    <link href="{% static 'css/animate.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'js/plugins/jquery-ui/jquery-ui.min.css' %}" rel="stylesheet">
    <style>
        .dataTables_filter input {border: 1px solid #ddd}
        td button {cursor: pointer}
    </style>
    {% block css %}
    {% endblock %}
</head>
<body>

<div id="wrapper">
    {% block main %}

    {% endblock %}
</div>

</body>
</html>

templates/left-right.html
{% extends "base-static.html" %}
{% load staticfiles %}

{% block main %}
    <nav class="navbar-default navbar-static-side" role="navigation">
        <div class="sidebar-collapse">
            <ul class="nav metismenu">
                <li class="nav-header">
                    <div class="dropdown profile-element">
                        <img alt="image" class="rounded-circle" src="/media/{{ request.user.headimage }}" width="48"
                             height="48"/>
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="block m-t-xs font-bold">{{ request.user.name }}</span>
                            <span class="text-muted text-xs block">{{ request.user.post|default_if_none:'员工' }} <b
                                    class="caret"></b></span>
                        </a>
                        <ul class="dropdown-menu animated fadeInRight m-t-xs">
                            <li><a class="dropdown-item" href="#"
                                   onclick="showPopup('个人信息',800,720,'{% url 'system:home-profile' %}');">个人信息</a>
                            </li>
                            <li><a class="dropdown-item" href="#"
                                   onclick="showPopup('修改登录密码',540,280,'{% url 'system:home-login_pwd_change' %}');">修改登录密码</a>
                            </li>
                            <li><a class="dropdown-item" href="#"
                                   onclick="showPopup('修改私有密码',540,280,'{% url 'system:home-private_pwd_change' %}');">修改私有密码</a>
                            </li>
                            <li class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="/logout/">登出</a></li>
                        </ul>
                    </div>
                    <div class="logo-element">
                        <img src="/static/img/logo2.png" width="50" height="50"/>
                    </div>
                </li>
            </ul>
            <ul class="nav metismenu" id="side-menu">
                {% block menu %}

                {% endblock %}
            </ul>
        </div>
    </nav>
    <div id="page-wrapper" class="gray-bg">
        <div class="row border-bottom">
            <nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars">
                        菜单</i>
                    </a>
                    <div class="minimalize-styl-2">
                        {% block Breadcrumb %}

                        {% endblock %}
                    </div>
                </div>
                <ul class="nav navbar-top-links navbar-right">
                    <li>
                        <span class="m-r-sm text-muted welcome-message">欢迎使用美和易思•莱芜School OA 系统</span>
                    </li>
                    {% block message %}
                    {% endblock %}
                    <li>
                        <a href="/logout/">
                            <i class="fa fa-sign-out"></i> 注销
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
        {% block header %}
        {% endblock %}
        <div class="wrapper wrapper-content animated fadeInRight">
            <div class="row">
                <div class="col-lg-12">
                    <div class="ibox ">
                        {% block content %}
                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
        <!--底部版权-->
        <div class="footer">
            <div class="float-right">
                <strong>美和易思&bull;莱芜School&nbsp;OA&nbsp;系统</strong>
            </div>
            <div>
                Copyright @莱芜校区学术团队 &copy; 2019-2020
            </div>
        </div>
        <!--底部版权END-->
    </div>
    <div class="modal inmodal" id="div_popup" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-lg" id="popup_dialog">
            <div class="modal-content animated fadeIn"><!--bounceInRight-->
                <div class="modal-header" style="padding: 5px">
                    <button type="button" class="close" data-dismiss="modal" style="margin:-0.3rem 0 -2rem auto">
                        <span aria-hidden="true">×</span>
                        <span class="sr-only">Close</span>
                    </button>
                    <h4 class="modal-title" id="h4_modal">aaa</h4>
                </div>
                <iframe scrolling="auto" allowtransparency="true" id="iframe_modal"
                        name="iframe_modal" onload="this.className='';" frameborder="0"></iframe>
            </div>
        </div>
    </div>

    <!-- Mainly scripts -->
    <script src="{% static 'js/jquery-3.3.1.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/plugins/metisMenu/jquery.metisMenu.js' %}"></script>
    <script src="{% static 'js/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>
    <script src="{% static 'js/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
    <!-- Custom and plugin javascript -->
    <script src="{% static 'js/inspinia.js' %}"></script>
    <script src="{% static 'js/plugins/pace/pace.min.js' %}"></script>
    <script>
        //关闭模态窗口
        function closePopup() {
            $('#div_popup').modal('hide');
        }

        $('.modal').draggable();

        //checkbox全选
        $("#checkAll").on("click", function () {
            if ($(this).prop("checked") === true) {
                $("input[name='checkList']").prop("checked", $(this).prop("checked"));
                $('#example tbody tr').addClass('selected');
            } else {
                $("input[name='checkList']").prop("checked", false);
                $('#example tbody tr').removeClass('selected');
            }
        });

        //删除
        function deleteData(toUrl, csrf_token, success_action, del_ids) {
            sId = "";
            if (del_ids) {
                sId = del_ids;
            } else {
                if ($("input[name='checkList']:checked").length == 0) {
                    swal('请选择要删除的记录', "", "warning");
                    return;
                }
                var arrId = new Array();
                $("input[name='checkList']:checked").each(function () {
                    arrId.push($(this).val());
                });

                sId = arrId.join(',');
            }
            swal({
                    title: "确定删除选中的信息吗？",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "删除",
                    cancelButtonText: "取消",
                    closeOnConfirm: false,
                },
                function (isConfirm) {
                    if (isConfirm) {
                        $.ajax({
                            type: "POST",
                            url: toUrl,
                            data: {"id": sId, csrfmiddlewaretoken: csrf_token},
                            cache: false,
                            success: function (msg) {
                                if (msg.result) {
                                    swal('操作成功', "", "success");
                                    success_action();
                                } else {
                                    //alert(msg.message);
                                    swal('操作失败', "", "warning");
                                }
                                return;
                            }
                        });
                    }
                });
        }

        $(function () {
            reveal_menu();
        });

        function reveal_menu() {
            var nav = document.getElementById("side-menu");
            var links = nav.getElementsByTagName("li");
            var lilen = nav.getElementsByTagName("a");
            var currenturl = document.location.href;
            var last = -1;
            for (var i = 0; i < links.length; i++) {
                var linkurl = lilen[i].getAttribute("href");
                if (currenturl.indexOf(linkurl) != -1) {
                    last = i;
                }
            }
            if (last == -1)
                return;
            links[last].className = "active";
            p = links[last].parentElement
            if (p.className == "nav nav-third-level collapse") {
                p.className = "nav nav-third-level collapse in"
                p.parentElement.className = 'active'
                p = p.parentElement.parentElement
            }
            if (p.className == "nav nav-second-level collapse") {
                p.className = "nav nav-second-level collapse in"
                p.parentElement.className = 'active'
            }
        }

        function showPopup(title,w,h,url) {
            $('#h4_modal').text(title);
            $("#popup_dialog").width(w);
            $('#iframe_modal').height(h);
            $('#iframe_modal').attr('src', url);
            $('#div_popup').modal({backdrop: 'static'});
        }
    </script>
    {% block menuscripts %}

    {% endblock %}
    {% block javascripts %}

    {% endblock %}

    {% block right_popup %}
    {% endblock %}

{% endblock %}

templates/page404.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>欢迎使用美和易思•莱芜School OA 系统</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/font-awesome/css/font-awesome.css" rel="stylesheet">
    <link href="/static/css/animate.css" rel="stylesheet">
    <link href="/static/css/style.css" rel="stylesheet">
</head>
<body class="gray-bg">
<div class="middle-box text-center animated fadeInDown">
    <h1>404</h1>
    <h3 class="font-bold">找不到网页</h3>
    <div class="error-desc">
        对不起，您正在寻找的页面已经找到。尝试检查URL的错误，然后按浏览器上的刷新按钮或尝试在我们的应用程序中找到其他内容。
        <form class="form-inline m-t" role="form">
            <div class="form-group">
                <input type="text" class="form-control" placeholder="请搜索你的内容">
            </div>
            <button type="submit" class="btn btn-primary">搜索</button>
        </form>
    </div>
</div>
<!-- Mainly scripts -->
<script src="/static/js/jquery-3.1.1.min.js"></script>
<script src="/static/js/popper.min.js"></script>
<script src="/static/js/bootstrap.js"></script>
</body>
</html>